version: 2

sources:
  - name: erp
    database: FEA24_4  
    schema: RAW_ADVENTURE_WORKS  
    tables:
      - name: SALESORDERHEADER
      - name: SALESORDERHEADERSALESREASON
      - name: SALESREASON
      - name: CREDITCARD

