version: 2

sources:
  - name: erp
    database: FEA24_4  
    schema: RAW_ADVENTURE_WORKS  
    tables:
      - name: SALESORDERHEADER
      - name: SALESORDERHEADERSALESREASON
      - name: SALESREASON
      - name: CREDITCARD
      - name: PRODUCT
      - name: SALESORDERDETAIL
      - name: CUSTOMER
      - name: PERSON
      - name: BUSINESSENTITYCONTACT
      - name: ADDRESS
      - name: STATEPROVINCE
      - name: COUNTRYREGION

      

